repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: yapf
        exclude: \*\.yaml
        entry: bash -c 'yapf "$@"; git add -u' --

